package net.pearadise.pearexpansion.util

import net.minecraft.block.Block
import net.minecraft.block.Blocks
import net.minecraft.item.Item
import net.minecraft.item.ItemConvertible
import net.pearadise.pearexpansion.block.ModBlocks
import net.pearadise.pearexpansion.block.VerticalSlabBlock
import net.pearadise.pearexpansion.item.ModItems
import net.pearadise.pearexpansion.util.ModContentLists.VERTICAL_TO_BASE_BLOCK

/**
 * Holds lists and maps of mod content for easy access and registration.
 *
 * This object helps organize blocks, items, and their relationships for the mod.
 */
object ModContentLists {

    /**
     * Maps each vertical slab block to its base block.
     *
     * Used for recipes, tooltips, or block logic.
     */
    val VERTICAL_TO_BASE_BLOCK: MutableMap<Block, Block> = mutableMapOf()

    /**
     * All custom items added by the mod.
     */
    val ALL_ITEMS: List<Item> = listOf(
        ModItems.PEAR,
        ModItems.GOLDEN_PEAR,
        ModItems.ENCHANTED_GOLDEN_PEAR
    )

    /**
     * All custom blocks added by the mod.
     */
    val ALL_BLOCKS: List<Block> = listOf(
        ModBlocks.OAK_VERTICAL_SLAB,
        ModBlocks.SPRUCE_VERTICAL_SLAB,
        ModBlocks.BIRCH_VERTICAL_SLAB,
        ModBlocks.JUNGLE_VERTICAL_SLAB,
        ModBlocks.ACACIA_VERTICAL_SLAB,
        ModBlocks.DARK_OAK_VERTICAL_SLAB,
        ModBlocks.MANGROVE_VERTICAL_SLAB,
        ModBlocks.PALE_OAK_VERTICAL_SLAB,
        ModBlocks.CHERRY_VERTICAL_SLAB,
        ModBlocks.BAMBOO_VERTICAL_SLAB,
        ModBlocks.BAMBOO_MOSAIC_VERTICAL_SLAB,
        ModBlocks.CRIMSON_VERTICAL_SLAB,
        ModBlocks.WARPED_VERTICAL_SLAB,
        ModBlocks.STONE_VERTICAL_SLAB,
        ModBlocks.SMOOTH_STONE_VERTICAL_SLAB,
        ModBlocks.SANDSTONE_VERTICAL_SLAB,
        ModBlocks.CUT_SANDSTONE_VERTICAL_SLAB,
        ModBlocks.COBBLESTONE_VERTICAL_SLAB,
        ModBlocks.BRICK_VERTICAL_SLAB,
        ModBlocks.STONE_BRICK_VERTICAL_SLAB,
        ModBlocks.NETHER_BRICK_VERTICAL_SLAB,
        ModBlocks.QUARTZ_VERTICAL_SLAB,
        ModBlocks.SMOOTH_QUARTZ_VERTICAL_SLAB,
        ModBlocks.RED_SANDSTONE_VERTICAL_SLAB,
        ModBlocks.CUT_RED_SANDSTONE_VERTICAL_SLAB,
        ModBlocks.PURPUR_VERTICAL_SLAB,
        ModBlocks.PRISMARINE_VERTICAL_SLAB,
        ModBlocks.PRISMARINE_BRICK_VERTICAL_SLAB,
        ModBlocks.DARK_PRISMARINE_VERTICAL_SLAB,
        ModBlocks.POLISHED_GRANITE_VERTICAL_SLAB,
        ModBlocks.SMOOTH_RED_SANDSTONE_VERTICAL_SLAB,
        ModBlocks.MOSSY_STONE_BRICK_VERTICAL_SLAB,
        ModBlocks.POLISHED_DIORITE_VERTICAL_SLAB,
        ModBlocks.MOSSY_COBBLESTONE_VERTICAL_SLAB,
        ModBlocks.END_STONE_BRICK_VERTICAL_SLAB,
        ModBlocks.SMOOTH_SANDSTONE_VERTICAL_SLAB,
        ModBlocks.GRANITE_VERTICAL_SLAB,
        ModBlocks.ANDESITE_VERTICAL_SLAB,
        ModBlocks.RED_NETHER_BRICK_VERTICAL_SLAB,
        ModBlocks.POLISHED_ANDESITE_VERTICAL_SLAB,
        ModBlocks.DIORITE_VERTICAL_SLAB,
        ModBlocks.COBBLED_DEEPSLATE_VERTICAL_SLAB,
        ModBlocks.POLISHED_DEEPSLATE_VERTICAL_SLAB,
        ModBlocks.DEEPSLATE_BRICK_VERTICAL_SLAB,
        ModBlocks.DEEPSLATE_TILE_VERTICAL_SLAB,
        ModBlocks.BLACKSTONE_VERTICAL_SLAB,
        ModBlocks.POLISHED_BLACKSTONE_VERTICAL_SLAB,
        ModBlocks.POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB,
        ModBlocks.CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.EXPOSED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.WEATHERED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.OXIDIZED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.WAXED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.WAXED_EXPOSED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.WAXED_WEATHERED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.WAXED_OXIDIZED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.MUD_BRICK_VERTICAL_SLAB,
        ModBlocks.RESIN_BRICK_VERTICAL_SLAB,
        ModBlocks.TUFF_VERTICAL_SLAB,
        ModBlocks.POLISHED_TUFF_VERTICAL_SLAB,
        ModBlocks.TUFF_BRICK_VERTICAL_SLAB
    )

    /**
     * Blocks that can be mined with an axe.
     */
    val AXE_MINEABLE_BLOCKS: List<Block> = listOf(
        ModBlocks.ACACIA_VERTICAL_SLAB,
        ModBlocks.BAMBOO_MOSAIC_VERTICAL_SLAB,
        ModBlocks.BAMBOO_VERTICAL_SLAB,
        ModBlocks.BIRCH_VERTICAL_SLAB,
        ModBlocks.CHERRY_VERTICAL_SLAB,
        ModBlocks.CRIMSON_VERTICAL_SLAB,
        ModBlocks.DARK_OAK_VERTICAL_SLAB,
        ModBlocks.JUNGLE_VERTICAL_SLAB,
        ModBlocks.MANGROVE_VERTICAL_SLAB,
        ModBlocks.OAK_VERTICAL_SLAB,
        ModBlocks.PALE_OAK_VERTICAL_SLAB,
        ModBlocks.SPRUCE_VERTICAL_SLAB,
        ModBlocks.WARPED_VERTICAL_SLAB
    )

    /**
     * Blocks that can be mined with a pickaxe.
     */
    val PICKAXE_MINEABLE_BLOCKS: List<Block> = listOf(
        ModBlocks.STONE_VERTICAL_SLAB,
        ModBlocks.SMOOTH_STONE_VERTICAL_SLAB,
        ModBlocks.SANDSTONE_VERTICAL_SLAB,
        ModBlocks.CUT_SANDSTONE_VERTICAL_SLAB,
        ModBlocks.COBBLESTONE_VERTICAL_SLAB,
        ModBlocks.BRICK_VERTICAL_SLAB,
        ModBlocks.STONE_BRICK_VERTICAL_SLAB,
        ModBlocks.NETHER_BRICK_VERTICAL_SLAB,
        ModBlocks.QUARTZ_VERTICAL_SLAB,
        ModBlocks.SMOOTH_QUARTZ_VERTICAL_SLAB,
        ModBlocks.RED_SANDSTONE_VERTICAL_SLAB,
        ModBlocks.CUT_RED_SANDSTONE_VERTICAL_SLAB,
        ModBlocks.PURPUR_VERTICAL_SLAB,
        ModBlocks.PRISMARINE_VERTICAL_SLAB,
        ModBlocks.PRISMARINE_BRICK_VERTICAL_SLAB,
        ModBlocks.DARK_PRISMARINE_VERTICAL_SLAB,
        ModBlocks.POLISHED_GRANITE_VERTICAL_SLAB,
        ModBlocks.SMOOTH_RED_SANDSTONE_VERTICAL_SLAB,
        ModBlocks.MOSSY_STONE_BRICK_VERTICAL_SLAB,
        ModBlocks.POLISHED_DIORITE_VERTICAL_SLAB,
        ModBlocks.MOSSY_COBBLESTONE_VERTICAL_SLAB,
        ModBlocks.END_STONE_BRICK_VERTICAL_SLAB,
        ModBlocks.SMOOTH_SANDSTONE_VERTICAL_SLAB,
        ModBlocks.GRANITE_VERTICAL_SLAB,
        ModBlocks.ANDESITE_VERTICAL_SLAB,
        ModBlocks.RED_NETHER_BRICK_VERTICAL_SLAB,
        ModBlocks.POLISHED_ANDESITE_VERTICAL_SLAB,
        ModBlocks.DIORITE_VERTICAL_SLAB,
        ModBlocks.COBBLED_DEEPSLATE_VERTICAL_SLAB,
        ModBlocks.POLISHED_DEEPSLATE_VERTICAL_SLAB,
        ModBlocks.DEEPSLATE_BRICK_VERTICAL_SLAB,
        ModBlocks.DEEPSLATE_TILE_VERTICAL_SLAB,
        ModBlocks.BLACKSTONE_VERTICAL_SLAB,
        ModBlocks.POLISHED_BLACKSTONE_VERTICAL_SLAB,
        ModBlocks.POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB,
        ModBlocks.CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.EXPOSED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.WEATHERED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.OXIDIZED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.WAXED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.WAXED_EXPOSED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.WAXED_WEATHERED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.WAXED_OXIDIZED_CUT_COPPER_VERTICAL_SLAB,
        ModBlocks.MUD_BRICK_VERTICAL_SLAB,
        ModBlocks.RESIN_BRICK_VERTICAL_SLAB,
        ModBlocks.TUFF_VERTICAL_SLAB,
        ModBlocks.POLISHED_TUFF_VERTICAL_SLAB,
        ModBlocks.TUFF_BRICK_VERTICAL_SLAB
    )

    /**
     * All items and blocks that can be used as an [ItemConvertible].
     */
    val ALL_ITEMS_CONVERTIBLE: List<ItemConvertible> =
        (ALL_ITEMS + ALL_BLOCKS).map { it as ItemConvertible }

    /**
     * All vertical slab blocks in the mod.
     */
    val ALL_VERTICAL_SLABS: List<Block> =
        ALL_BLOCKS.filterIsInstance<VerticalSlabBlock>()

    /**
     * Initializes the [VERTICAL_TO_BASE_BLOCK] map with vertical slab to base block pairs.
     */
    init {
        VERTICAL_TO_BASE_BLOCK[ModBlocks.ACACIA_VERTICAL_SLAB] = Blocks.ACACIA_PLANKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.ANDESITE_VERTICAL_SLAB] = Blocks.ANDESITE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.BAMBOO_MOSAIC_VERTICAL_SLAB] = Blocks.BAMBOO_MOSAIC
        VERTICAL_TO_BASE_BLOCK[ModBlocks.BAMBOO_VERTICAL_SLAB] = Blocks.BAMBOO_PLANKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.BIRCH_VERTICAL_SLAB] = Blocks.BIRCH_PLANKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.BLACKSTONE_VERTICAL_SLAB] = Blocks.BLACKSTONE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.BRICK_VERTICAL_SLAB] = Blocks.BRICKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.CHERRY_VERTICAL_SLAB] = Blocks.CHERRY_PLANKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.COBBLED_DEEPSLATE_VERTICAL_SLAB] = Blocks.COBBLED_DEEPSLATE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.COBBLESTONE_VERTICAL_SLAB] = Blocks.COBBLESTONE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.CRIMSON_VERTICAL_SLAB] = Blocks.CRIMSON_PLANKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.CUT_COPPER_VERTICAL_SLAB] = Blocks.CUT_COPPER
        VERTICAL_TO_BASE_BLOCK[ModBlocks.CUT_RED_SANDSTONE_VERTICAL_SLAB] = Blocks.CUT_RED_SANDSTONE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.CUT_SANDSTONE_VERTICAL_SLAB] = Blocks.CUT_SANDSTONE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.DARK_OAK_VERTICAL_SLAB] = Blocks.DARK_OAK_PLANKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.DARK_PRISMARINE_VERTICAL_SLAB] = Blocks.DARK_PRISMARINE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.DEEPSLATE_BRICK_VERTICAL_SLAB] = Blocks.DEEPSLATE_BRICKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.DEEPSLATE_TILE_VERTICAL_SLAB] = Blocks.DEEPSLATE_TILES
        VERTICAL_TO_BASE_BLOCK[ModBlocks.DIORITE_VERTICAL_SLAB] = Blocks.DIORITE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.END_STONE_BRICK_VERTICAL_SLAB] = Blocks.END_STONE_BRICKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.EXPOSED_CUT_COPPER_VERTICAL_SLAB] = Blocks.EXPOSED_CUT_COPPER
        VERTICAL_TO_BASE_BLOCK[ModBlocks.GRANITE_VERTICAL_SLAB] = Blocks.GRANITE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.JUNGLE_VERTICAL_SLAB] = Blocks.JUNGLE_PLANKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.MANGROVE_VERTICAL_SLAB] = Blocks.MANGROVE_PLANKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.MOSSY_COBBLESTONE_VERTICAL_SLAB] = Blocks.MOSSY_COBBLESTONE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.MOSSY_STONE_BRICK_VERTICAL_SLAB] = Blocks.MOSSY_STONE_BRICKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.MUD_BRICK_VERTICAL_SLAB] = Blocks.MUD_BRICKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.NETHER_BRICK_VERTICAL_SLAB] = Blocks.NETHER_BRICKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.OAK_VERTICAL_SLAB] = Blocks.OAK_PLANKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.OXIDIZED_CUT_COPPER_VERTICAL_SLAB] = Blocks.OXIDIZED_CUT_COPPER
        VERTICAL_TO_BASE_BLOCK[ModBlocks.PALE_OAK_VERTICAL_SLAB] = Blocks.PALE_OAK_PLANKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.POLISHED_ANDESITE_VERTICAL_SLAB] = Blocks.POLISHED_ANDESITE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB] = Blocks.POLISHED_BLACKSTONE_BRICKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.POLISHED_BLACKSTONE_VERTICAL_SLAB] = Blocks.POLISHED_BLACKSTONE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.POLISHED_DEEPSLATE_VERTICAL_SLAB] = Blocks.POLISHED_DEEPSLATE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.POLISHED_DIORITE_VERTICAL_SLAB] = Blocks.POLISHED_DIORITE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.POLISHED_GRANITE_VERTICAL_SLAB] = Blocks.POLISHED_GRANITE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.POLISHED_TUFF_VERTICAL_SLAB] = Blocks.POLISHED_TUFF
        VERTICAL_TO_BASE_BLOCK[ModBlocks.PRISMARINE_BRICK_VERTICAL_SLAB] = Blocks.PRISMARINE_BRICKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.PRISMARINE_VERTICAL_SLAB] = Blocks.PRISMARINE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.PURPUR_VERTICAL_SLAB] = Blocks.PURPUR_BLOCK
        VERTICAL_TO_BASE_BLOCK[ModBlocks.QUARTZ_VERTICAL_SLAB] = Blocks.QUARTZ_BLOCK
        VERTICAL_TO_BASE_BLOCK[ModBlocks.RED_NETHER_BRICK_VERTICAL_SLAB] = Blocks.RED_NETHER_BRICKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.RED_SANDSTONE_VERTICAL_SLAB] = Blocks.RED_SANDSTONE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.RESIN_BRICK_VERTICAL_SLAB] = Blocks.RESIN_BRICKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.SANDSTONE_VERTICAL_SLAB] = Blocks.SANDSTONE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.SMOOTH_QUARTZ_VERTICAL_SLAB] = Blocks.SMOOTH_QUARTZ
        VERTICAL_TO_BASE_BLOCK[ModBlocks.SMOOTH_RED_SANDSTONE_VERTICAL_SLAB] = Blocks.SMOOTH_RED_SANDSTONE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.SMOOTH_SANDSTONE_VERTICAL_SLAB] = Blocks.SMOOTH_SANDSTONE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.SMOOTH_STONE_VERTICAL_SLAB] = Blocks.SMOOTH_STONE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.SPRUCE_VERTICAL_SLAB] = Blocks.SPRUCE_PLANKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.STONE_BRICK_VERTICAL_SLAB] = Blocks.STONE_BRICKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.STONE_VERTICAL_SLAB] = Blocks.STONE
        VERTICAL_TO_BASE_BLOCK[ModBlocks.TUFF_BRICK_VERTICAL_SLAB] = Blocks.TUFF_BRICKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.TUFF_VERTICAL_SLAB] = Blocks.TUFF
        VERTICAL_TO_BASE_BLOCK[ModBlocks.WARPED_VERTICAL_SLAB] = Blocks.WARPED_PLANKS
        VERTICAL_TO_BASE_BLOCK[ModBlocks.WAXED_CUT_COPPER_VERTICAL_SLAB] = Blocks.WAXED_CUT_COPPER
        VERTICAL_TO_BASE_BLOCK[ModBlocks.WAXED_EXPOSED_CUT_COPPER_VERTICAL_SLAB] = Blocks.WAXED_EXPOSED_CUT_COPPER
        VERTICAL_TO_BASE_BLOCK[ModBlocks.WAXED_OXIDIZED_CUT_COPPER_VERTICAL_SLAB] = Blocks.WAXED_OXIDIZED_CUT_COPPER
        VERTICAL_TO_BASE_BLOCK[ModBlocks.WAXED_WEATHERED_CUT_COPPER_VERTICAL_SLAB] = Blocks.WAXED_WEATHERED_CUT_COPPER
        VERTICAL_TO_BASE_BLOCK[ModBlocks.WEATHERED_CUT_COPPER_VERTICAL_SLAB] = Blocks.WEATHERED_CUT_COPPER
    }
}