package net.pearadise.pearexpansion.util;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.ItemConvertible;
import net.pearadise.pearexpansion.block.ModBlocks;
import net.pearadise.pearexpansion.block.VerticalSlabBlock;
import net.pearadise.pearexpansion.item.ModItems;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

public class ModContentLists {

    public static final Map<Block, Block> VERTICAL_TO_BASE_BLOCK = new HashMap<>();
    public static final List<Item> ALL_ITEMS = List.of(
            ModItems.PEAR,
            ModItems.GOLDEN_PEAR,
            ModItems.ENCHANTED_GOLDEN_PEAR
    );
    public static final List<Block> ALL_BLOCKS = List.of(

            ModBlocks.VERTICAL_OAK_SLAB,
            ModBlocks.VERTICAL_SPRUCE_SLAB,
            ModBlocks.VERTICAL_BIRCH_SLAB,
            ModBlocks.VERTICAL_JUNGLE_SLAB,
            ModBlocks.VERTICAL_ACACIA_SLAB,
            ModBlocks.VERTICAL_DARK_OAK_SLAB,
            ModBlocks.VERTICAL_MANGROVE_SLAB,
            ModBlocks.VERTICAL_PALE_OAK_SLAB,
            ModBlocks.VERTICAL_CHERRY_SLAB,
            ModBlocks.VERTICAL_BAMBOO_SLAB,
            ModBlocks.VERTICAL_BAMBOO_MOSAIC_SLAB,
            ModBlocks.VERTICAL_CRIMSON_SLAB,
            ModBlocks.VERTICAL_WARPED_SLAB,
            ModBlocks.VERTICAL_STONE_SLAB,
            ModBlocks.VERTICAL_SMOOTH_STONE_SLAB,
            ModBlocks.VERTICAL_SANDSTONE_SLAB,
            ModBlocks.VERTICAL_CUT_SANDSTONE_SLAB,
            ModBlocks.VERTICAL_COBBLESTONE_SLAB,
            ModBlocks.VERTICAL_BRICK_SLAB,
            ModBlocks.VERTICAL_STONE_BRICK_SLAB,
            ModBlocks.VERTICAL_NETHER_BRICK_SLAB,
            ModBlocks.VERTICAL_QUARTZ_SLAB,
            ModBlocks.VERTICAL_SMOOTH_QUARTZ_SLAB,
            ModBlocks.VERTICAL_RED_SANDSTONE_SLAB,
            ModBlocks.VERTICAL_CUT_RED_SANDSTONE_SLAB,
            ModBlocks.VERTICAL_PURPUR_SLAB,
            ModBlocks.VERTICAL_PRISMARINE_SLAB,
            ModBlocks.VERTICAL_PRISMARINE_BRICK_SLAB,
            ModBlocks.VERTICAL_DARK_PRISMARINE_SLAB,
            ModBlocks.VERTICAL_POLISHED_GRANITE_SLAB,
            ModBlocks.VERTICAL_SMOOTH_RED_SANDSTONE_SLAB,
            ModBlocks.VERTICAL_MOSSY_STONE_BRICK_SLAB,

            ModBlocks.VERTICAL_POLISHED_DIORITE_SLAB,
            ModBlocks.VERTICAL_MOSSY_COBBLESTONE_SLAB,
            ModBlocks.VERTICAL_END_STONE_BRICK_SLAB,
            ModBlocks.VERTICAL_SMOOTH_SANDSTONE_SLAB,
            ModBlocks.VERTICAL_GRANITE_SLAB,
            ModBlocks.VERTICAL_ANDESITE_SLAB,
            ModBlocks.VERTICAL_RED_NETHER_BRICK_SLAB,
            ModBlocks.VERTICAL_POLISHED_ANDESITE_SLAB,
            ModBlocks.VERTICAL_DIORITE_SLAB,
            ModBlocks.VERTICAL_COBBLED_DEEPSLATE_SLAB,
            ModBlocks.VERTICAL_POLISHED_DEEPSLATE_SLAB,
            ModBlocks.VERTICAL_DEEPSLATE_BRICK_SLAB,
            ModBlocks.VERTICAL_DEEPSLATE_TILE_SLAB,
            ModBlocks.VERTICAL_BLACKSTONE_SLAB,
            ModBlocks.VERTICAL_POLISHED_BLACKSTONE_SLAB,
            ModBlocks.VERTICAL_POLISHED_BLACKSTONE_BRICK_SLAB,
            ModBlocks.VERTICAL_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_EXPOSED_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_WEATHERED_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_OXIDIZED_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_WAXED_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_WAXED_EXPOSED_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_WAXED_WEATHERED_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_WAXED_OXIDIZED_CUT_COPPER_SLAB,

            ModBlocks.VERTICAL_MUD_BRICK_SLAB,
            ModBlocks.VERTICAL_RESIN_BRICK_SLAB,

            ModBlocks.VERTICAL_TUFF_SLAB,
            ModBlocks.VERTICAL_POLISHED_TUFF_SLAB,
            ModBlocks.VERTICAL_TUFF_BRICK_SLAB);
    public static final List<Block> AXE_MINEABLE_BLOCKS = List.of(
            ModBlocks.VERTICAL_ACACIA_SLAB,
            ModBlocks.VERTICAL_BAMBOO_MOSAIC_SLAB,
            ModBlocks.VERTICAL_BAMBOO_SLAB,
            ModBlocks.VERTICAL_BIRCH_SLAB,
            ModBlocks.VERTICAL_CHERRY_SLAB,
            ModBlocks.VERTICAL_CRIMSON_SLAB,
            ModBlocks.VERTICAL_DARK_OAK_SLAB,
            ModBlocks.VERTICAL_JUNGLE_SLAB,
            ModBlocks.VERTICAL_MANGROVE_SLAB,
            ModBlocks.VERTICAL_OAK_SLAB,
            ModBlocks.VERTICAL_PALE_OAK_SLAB,
            ModBlocks.VERTICAL_SPRUCE_SLAB,
            ModBlocks.VERTICAL_WARPED_SLAB);
    public static final List<Block> PICKAXE_MINEABLE_BLOCKS = List.of(
            ModBlocks.VERTICAL_STONE_SLAB,
            ModBlocks.VERTICAL_SMOOTH_STONE_SLAB,
            ModBlocks.VERTICAL_SANDSTONE_SLAB,
            ModBlocks.VERTICAL_CUT_SANDSTONE_SLAB,
            ModBlocks.VERTICAL_COBBLESTONE_SLAB,
            ModBlocks.VERTICAL_BRICK_SLAB,
            ModBlocks.VERTICAL_STONE_BRICK_SLAB,
            ModBlocks.VERTICAL_NETHER_BRICK_SLAB,
            ModBlocks.VERTICAL_QUARTZ_SLAB,
            ModBlocks.VERTICAL_SMOOTH_QUARTZ_SLAB,
            ModBlocks.VERTICAL_RED_SANDSTONE_SLAB,
            ModBlocks.VERTICAL_CUT_RED_SANDSTONE_SLAB,
            ModBlocks.VERTICAL_PURPUR_SLAB,
            ModBlocks.VERTICAL_PRISMARINE_SLAB,
            ModBlocks.VERTICAL_PRISMARINE_BRICK_SLAB,
            ModBlocks.VERTICAL_DARK_PRISMARINE_SLAB,
            ModBlocks.VERTICAL_POLISHED_GRANITE_SLAB,
            ModBlocks.VERTICAL_SMOOTH_RED_SANDSTONE_SLAB,
            ModBlocks.VERTICAL_MOSSY_STONE_BRICK_SLAB,
            ModBlocks.VERTICAL_POLISHED_DIORITE_SLAB,
            ModBlocks.VERTICAL_MOSSY_COBBLESTONE_SLAB,

            ModBlocks.VERTICAL_END_STONE_BRICK_SLAB,
            ModBlocks.VERTICAL_SMOOTH_SANDSTONE_SLAB,
            ModBlocks.VERTICAL_GRANITE_SLAB,
            ModBlocks.VERTICAL_ANDESITE_SLAB,
            ModBlocks.VERTICAL_RED_NETHER_BRICK_SLAB,
            ModBlocks.VERTICAL_POLISHED_ANDESITE_SLAB,
            ModBlocks.VERTICAL_DIORITE_SLAB,
            ModBlocks.VERTICAL_COBBLED_DEEPSLATE_SLAB,
            ModBlocks.VERTICAL_POLISHED_DEEPSLATE_SLAB,
            ModBlocks.VERTICAL_DEEPSLATE_BRICK_SLAB,
            ModBlocks.VERTICAL_DEEPSLATE_TILE_SLAB,
            ModBlocks.VERTICAL_BLACKSTONE_SLAB,
            ModBlocks.VERTICAL_POLISHED_BLACKSTONE_SLAB,
            ModBlocks.VERTICAL_POLISHED_BLACKSTONE_BRICK_SLAB,
            ModBlocks.VERTICAL_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_EXPOSED_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_WEATHERED_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_OXIDIZED_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_WAXED_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_WAXED_EXPOSED_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_WAXED_WEATHERED_CUT_COPPER_SLAB,
            ModBlocks.VERTICAL_WAXED_OXIDIZED_CUT_COPPER_SLAB,

            ModBlocks.VERTICAL_MUD_BRICK_SLAB,
            ModBlocks.VERTICAL_RESIN_BRICK_SLAB,

            ModBlocks.VERTICAL_TUFF_SLAB,
            ModBlocks.VERTICAL_POLISHED_TUFF_SLAB,
            ModBlocks.VERTICAL_TUFF_BRICK_SLAB
    );
    public static final List<ItemConvertible> ALL_ITEMS_CONVERTIBLE =
            Stream.of(
                    ALL_ITEMS.toArray(new ItemConvertible[0]),
                    ALL_BLOCKS.toArray(new ItemConvertible[0])
            ).flatMap(Stream::of).toList();
    public static final List<Block> ALL_VERTICAL_SLABS = ALL_BLOCKS
            .stream()
            .filter(block -> block instanceof VerticalSlabBlock)
            .toList();

    static {
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_ACACIA_SLAB, Blocks.ACACIA_PLANKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_ANDESITE_SLAB, Blocks.ANDESITE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_BAMBOO_MOSAIC_SLAB, Blocks.BAMBOO_MOSAIC);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_BAMBOO_SLAB, Blocks.BAMBOO_PLANKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_BIRCH_SLAB, Blocks.BIRCH_PLANKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_BLACKSTONE_SLAB, Blocks.BLACKSTONE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_BRICK_SLAB, Blocks.BRICKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_CHERRY_SLAB, Blocks.CHERRY_PLANKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_COBBLED_DEEPSLATE_SLAB, Blocks.COBBLED_DEEPSLATE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_COBBLESTONE_SLAB, Blocks.COBBLESTONE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_CRIMSON_SLAB, Blocks.CRIMSON_PLANKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_CUT_COPPER_SLAB, Blocks.CUT_COPPER);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_CUT_RED_SANDSTONE_SLAB, Blocks.CUT_RED_SANDSTONE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_CUT_SANDSTONE_SLAB, Blocks.CUT_SANDSTONE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_DARK_OAK_SLAB, Blocks.DARK_OAK_PLANKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_DARK_PRISMARINE_SLAB, Blocks.DARK_PRISMARINE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_DEEPSLATE_BRICK_SLAB, Blocks.DEEPSLATE_BRICKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_DEEPSLATE_TILE_SLAB, Blocks.DEEPSLATE_TILES);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_DIORITE_SLAB, Blocks.DIORITE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_END_STONE_BRICK_SLAB, Blocks.END_STONE_BRICKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_EXPOSED_CUT_COPPER_SLAB, Blocks.EXPOSED_CUT_COPPER);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_GRANITE_SLAB, Blocks.GRANITE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_JUNGLE_SLAB, Blocks.JUNGLE_PLANKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_MANGROVE_SLAB, Blocks.MANGROVE_PLANKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_MOSSY_COBBLESTONE_SLAB, Blocks.MOSSY_COBBLESTONE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_MOSSY_STONE_BRICK_SLAB, Blocks.MOSSY_STONE_BRICKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_MUD_BRICK_SLAB, Blocks.MUD_BRICKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_NETHER_BRICK_SLAB, Blocks.NETHER_BRICKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_OAK_SLAB, Blocks.OAK_PLANKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_OXIDIZED_CUT_COPPER_SLAB, Blocks.OXIDIZED_CUT_COPPER);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_PALE_OAK_SLAB, Blocks.PALE_OAK_PLANKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_POLISHED_ANDESITE_SLAB, Blocks.POLISHED_ANDESITE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_POLISHED_BLACKSTONE_BRICK_SLAB, Blocks.POLISHED_BLACKSTONE_BRICKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_POLISHED_BLACKSTONE_SLAB, Blocks.POLISHED_BLACKSTONE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_POLISHED_DEEPSLATE_SLAB, Blocks.POLISHED_DEEPSLATE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_POLISHED_DIORITE_SLAB, Blocks.POLISHED_DIORITE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_POLISHED_GRANITE_SLAB, Blocks.POLISHED_GRANITE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_POLISHED_TUFF_SLAB, Blocks.POLISHED_TUFF);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_PRISMARINE_BRICK_SLAB, Blocks.PRISMARINE_BRICKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_PRISMARINE_SLAB, Blocks.PRISMARINE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_PURPUR_SLAB, Blocks.PURPUR_BLOCK);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_QUARTZ_SLAB, Blocks.QUARTZ_BLOCK);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_RED_NETHER_BRICK_SLAB, Blocks.RED_NETHER_BRICKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_RED_SANDSTONE_SLAB, Blocks.RED_SANDSTONE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_RESIN_BRICK_SLAB, Blocks.RESIN_BRICKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_SANDSTONE_SLAB, Blocks.SANDSTONE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_SMOOTH_QUARTZ_SLAB, Blocks.SMOOTH_QUARTZ);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_SMOOTH_RED_SANDSTONE_SLAB, Blocks.SMOOTH_RED_SANDSTONE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_SMOOTH_SANDSTONE_SLAB, Blocks.SMOOTH_SANDSTONE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_SMOOTH_STONE_SLAB, Blocks.SMOOTH_STONE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_SPRUCE_SLAB, Blocks.SPRUCE_PLANKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_STONE_BRICK_SLAB, Blocks.STONE_BRICKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_STONE_SLAB, Blocks.STONE);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_TUFF_BRICK_SLAB, Blocks.TUFF_BRICKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_TUFF_SLAB, Blocks.TUFF);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_WARPED_SLAB, Blocks.WARPED_PLANKS);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_WAXED_CUT_COPPER_SLAB, Blocks.WAXED_CUT_COPPER);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_WAXED_EXPOSED_CUT_COPPER_SLAB, Blocks.WAXED_EXPOSED_CUT_COPPER);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_WAXED_OXIDIZED_CUT_COPPER_SLAB, Blocks.WAXED_OXIDIZED_CUT_COPPER);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_WAXED_WEATHERED_CUT_COPPER_SLAB, Blocks.WAXED_WEATHERED_CUT_COPPER);
        VERTICAL_TO_BASE_BLOCK.put(ModBlocks.VERTICAL_WEATHERED_CUT_COPPER_SLAB, Blocks.WEATHERED_CUT_COPPER);
    }

}
