name: CI - Gradle Build (Java 21)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build (Java 21)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Cache Gradle wrapper and caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Show Java info
        run: java -version

      - name: Build with Gradle (verbose)
        run: ./gradlew clean build --no-daemon --stacktrace --info
        env:
          GRADLE_OPTS: -Xmx2g -Dorg.gradle.jvmargs=-Xmx2g

  dependency-submission:
    name: Generate & submit dependency graph
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 (for dependency submission)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
